%YAML:1.0

# Input Type
Input.type: "Camera"
#Input.type: "Sequence"

Input.Sequence.pattern: 'E:\Gangwan-street\2\rect%05d.jpg'
Input.Sequence.begin: 0
Input.Sequence.step: 1

# Input.video.filename: ''

# Camera calibration data.
Calib.fx: 749
Calib.fy: 749
Calib.cx: 479.5
Calib.cy: 269.5

# FAST feature detector parameters.
FAST.threshold: 20
FAST.spread: 20     # Features are spreaded using grid

Initializer.matchWindow: 2

RANSAC.sigma: 3.0
RANSAC.successRate: 0.99
RANSAC.maxIteration: 100

# RANSAC.Essential.sigma: 1.0
# RANSAC.Essential.successRate: 0.99
# RANSAC.Essential.maxIteration: 200

# RANSAC.Homography.sigma: 1.0
# RANSAC.Homography.successRate: 0.99
# RANSAC.Homography.maxIteration: 200
